name: FertileCrops
version: 1.0
main: me.FertileCrops.FertileCrops
api-version: '1.20'
commands: 
  fertilecrops:
    description: FertileCrops management command
    usage: /<command> help>
    aliases: [fc]
    permission: fertilecrops.admin
    permission-message: You don’t have permission to use this command!
