name: FertileCrops
version: 1.0
main: me.FertileCrops.FertileCrops
api-version: '1.21'
commands: 
  fertilecrops:
    description: FertileCrops management command
    usage: /<command> <crop|withered|cost|rate|radius|reload>
    aliases: [fc]
    permission: fertilecrops.admin
    permission-message: You don’t have permission to use this command!
