# Radius in blocks around the crop to spread
spread-radius: 3

# Chance (0.0 - 1.0) that a new crop successfully grows
success-chance: 0.7

# XP cost per spread
xp-cost: 1

# Blocks that failed attempts can turn into
withered-blocks:
  - DIRT
  - COARSE_DIRT
  - SAND

# Allowed crops/seeds for Fertile Growth
allowed-crops:
  WHEAT: true
  CARROT: true
  POTATO: true
  BEETROOT: true
  PUMPKIN: false
  MELON: false
  COCOA: false
  SUGAR_CANE: false

